### ISSUE TITLE
Identify shared components across all pages

### ISSUE THREAD

**Issue by pharaouk** [openface-ai/platform#1]
Identify all shared components in the listed feature specs:

https://github.com/openface-ai/platform/wiki

And provide a comprehensive list of these in order to streamline development. 
After identifying components, we will delegate accordingly.

**Comment by hkrishnaa0** [comment]
## Layout 
1. Page Container
2. Grid Layout
3. Flex Container

## Navigation
1. Breadcrumb
2. Sidebar
3. Tabs Navigation

## Form
1. Text Input
2. Dropdown Select
3. Checkbox/Toggle
4. Date Picker
5. File Upload

## Data Display 
1. Repository Card
2. File Preview
3. Metadata Display
4. User Avatar

## Alert 
1. Toast Notification
2. Modal Dialog
3. Loading Spinner
4. Error Message
5. Tooltip

## Utility 
1. Copy Button
2. Search Bar
3. Confirmation Prompt
4. Pagination
5. Filter Selector

## Interactive 
1.  Button
2. Dropdown Menu
4. Progress Indicator


## Specialized
1. OAuth Login Buttons
2. API Key Generator
3. Visibility Toggle
4. Version Selector
5. Repository Selector

This is all i could think of, feel free to add to it

**Comment by hkrishnaa0** [comment]
## Layout
1. Page Container
   - Responsive page wrapper
   - Consistent structural layout
   - Handles page-level spacing and alignment

2. Grid Layout
   - Flexible content organization
   - Responsive column management
   - Adaptive content positioning

3. Flex Container
   - Dynamic content arrangement
   - Flexible alignment options
   - Direction and spacing control

## Navigation
1. Breadcrumb
   - Hierarchical location tracking
   - Clickable navigation path
   - User orientation mechanism

2. Sidebar
   - Collapsible main navigation
   - Section management
   - Context-aware menu highlighting

3. Tabs Navigation
   - Sectional content switching
   - Clear interaction state
   - Horizontal/vertical layouts

## Form
1. Text Input
   - Flexible data entry
   - Real-time validation
   - Multiple input type support

2. Dropdown Select
   - Option selection interface
   - Multi/single selection
   - Search and filtering capabilities

3. Checkbox/Toggle
   - Boolean option management
   - Binary state representation
   - Feature/setting activation

4. Date Picker
   - Calendar-based date selection
   - Range and single date support
   - Timezone considerations

5. File Upload
   - Drag-and-drop interface
   - File type validation
   - Progress tracking

## Data Display
1. Repository Card
   - Compact repository summary
   - Metadata visualization
   - Interaction statistics

2. File Preview
   - Inline content rendering
   - Syntax highlighting
   - Multiple format support

3. Metadata Display
   - Structured information presentation
   - Key-value visualization
   - Copyable content

4. User Avatar
   - Profile image representation
   - Fallback initial display
   - Flexible sizing

## Alert
1. Toast Notification
   - Non-blocking message system
   - Temporary status updates
   - Multiple severity levels

2. Modal Dialog
   - Overlay interaction interface
   - Critical action confirmations
   - Contextual information display

3. Loading Spinner
   - Background process indicator
   - Async operation feedback
   - Customizable visual styles

4. Error Message
   - Structured error communication
   - Detailed problem description
   - Potential resolution guidance

5. Tooltip
   - Contextual information overlay
   - Hover-based explanations
   - Additional context provider

## Utility
1. Copy Button
   - Instant content clipboard transfer
   - Feedback on successful copy
   - Clipboard integration

2. Search Bar
   - Advanced content discovery
   - Filtering and autocomplete
   - Global/localized search

3. Confirmation Prompt
   - Action validation interface
   - Critical change protection
   - Customizable messaging

4. Pagination
   - Content list navigation
   - Page management
   - Results per page control

5. Filter Selector
   - Advanced content filtering
   - Multi-dimensional sorting
   - Dynamic query building

## Interactive
1. Button
   - Action trigger mechanism
   - Multiple style variants
   - State management

2. Dropdown Menu
   - Expandable action list
   - Context-based options
   - Nested menu support

3. Progress Indicator
   - Step/stage tracking
   - Process completion visualization
   - Horizontal/vertical layouts

## Specialized
1. OAuth Login Buttons
   - Third-party authentication
   - Simplified login process
   - Provider-specific styling

2. API Key Generator
   - Secure token creation
   - Clipboard integration
   - Regeneration support

3. Visibility Toggle
   - Public/private switching
   - Access control mechanism
   - Instant state change

4. Version Selector
   - Model/dataset versioning
   - Comparative version display
   - Rollback capabilities

5. Repository Selector
   - Multi-repository management
   - Quick context switching
   - Filtered repository view
